/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as PublicRouteRouteImport } from './../../routes/_public/route'
import { Route as PrivateRouteRouteImport } from './../../routes/_private/route'
import { Route as PrivateEmployeeRouteRouteImport } from './../../routes/_private/employee/route'
import { Route as PrivateHomeRouteRouteImport } from './../../routes/_private/_home/route'
import { Route as PublicAuthLoginRouteImport } from './../../routes/_public/auth/login'
import { Route as PrivateDemoDataGridRouteRouteImport } from './../../routes/_private/demo/data-grid/route'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateEmployeeRouteRoute = PrivateEmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateHomeRouteRoute = PrivateHomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateDemoDataGridRouteRoute =
  PrivateDemoDataGridRouteRouteImport.update({
    id: '/demo/data-grid',
    path: '/demo/data-grid',
    getParentRoute: () => PrivateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateHomeRouteRoute
  '/employee': typeof PrivateEmployeeRouteRoute
  '/demo/data-grid': typeof PrivateDemoDataGridRouteRoute
  '/auth/login': typeof PublicAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateHomeRouteRoute
  '/employee': typeof PrivateEmployeeRouteRoute
  '/demo/data-grid': typeof PrivateDemoDataGridRouteRoute
  '/auth/login': typeof PublicAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/_home': typeof PrivateHomeRouteRoute
  '/_private/employee': typeof PrivateEmployeeRouteRoute
  '/_private/demo/data-grid': typeof PrivateDemoDataGridRouteRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employee' | '/demo/data-grid' | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employee' | '/demo/data-grid' | '/auth/login'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/_home'
    | '/_private/employee'
    | '/_private/demo/data-grid'
    | '/_public/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/employee': {
      id: '/_private/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof PrivateEmployeeRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_home': {
      id: '/_private/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateHomeRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/demo/data-grid': {
      id: '/_private/demo/data-grid'
      path: '/demo/data-grid'
      fullPath: '/demo/data-grid'
      preLoaderRoute: typeof PrivateDemoDataGridRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivateRouteRouteChildren {
  PrivateHomeRouteRoute: typeof PrivateHomeRouteRoute
  PrivateEmployeeRouteRoute: typeof PrivateEmployeeRouteRoute
  PrivateDemoDataGridRouteRoute: typeof PrivateDemoDataGridRouteRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateHomeRouteRoute: PrivateHomeRouteRoute,
  PrivateEmployeeRouteRoute: PrivateEmployeeRouteRoute,
  PrivateDemoDataGridRouteRoute: PrivateDemoDataGridRouteRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
